[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "clingo",
    "textwrap",
    "nnf",
    "itertools",
    "copy",
    "math",
    "abc",
    "typing",
    "pyparsing"
]

build-backend = "setuptools.build_meta"